### ISSUE TITLE
Memory requirements 

### ISSUE THREAD

**Issue by bhack** [yeates/DMT#1]
In 6.6 section of the paper
> Firstly, while our method exhibits ro-
bustness to random video shapes, one common drawback of
Transformers-based methods [25, 53, 23] is their high mem-
ory requirements when processing high-resolution content,
such as 1080p videos.

Do you have any memory requirement to share at specific input resolution?

**Comment by yeates** [comment]
During the training phase, our model is trained on frames with a resolution of 432x240 on A100. Each training batch consists of 8 frames as input. During the inference phase, a single batch may contain more frames, usually ranging from 10 to 18 frames. The model is evaluated on a 3090 GPU, so we recommend using a GPU with at least 24GB of memory to run our model smoothly.

Alternatively, to accommodate different GPU memory capacities, you have the flexibility to adjust the number of input frames or the input resolution accordingly.

**Comment by bhack** [comment]
Thanks so e.g. with 24GB what Is the inference input res you could handle?

**Comment by yeates** [comment]
Using res of 432 * 240, it will work well with the same training resolution.

**Comment by bhack** [comment]
So I suppose that at inference time, also at batch 1, we will have some hard constraint on the transformer attention to scale up the input resolution right?

**Comment by bhack** [comment]
Have you explored a more efficient transformer design like:
https://github.com/mit-han-lab/efficientvit (ICCV 2023)
https://github.com/microsoft/Cream/tree/main/EfficientViT (CVPR 2023)

**Comment by yeates** [comment]
Your suggestions are excellent! Efficient attention is indeed one of my next research focuses. Techniques such as xformer, flash-attention v2, retnet, and those you mentioned will be among the ones I'll explore. Unfortunately, they won't be included in the upcoming release, but please stay tuned for my future progress!

**Comment by bhack** [comment]
Yes I think that in the video inpainting we are not incentivized to test perf at more then `432 * 240` as it is now a sort of de-facto standard. This is causing a quite large GAP in including efficiency research. 

But the highres datasets are already here:
Davis full-res instead of Davis 480p, [YouTube VOS 2023](https://codalab.lisn.upsaclay.fr/competitions/13524), [BURST](https://github.com/Ali2500/BURST-benchmark) etc..
Probably also expanding over a more in-painting oriented benchmark could be also useful:
https://github.com/MichiganCOG/devil

Let me know when you have any update about upscaling the resolution with a more efficient Transformer/MHSA

**Comment by yeates** [comment]
As soon as there's progress or new research, I'll let you know. Stay tuned, and if you have any other questions or specific interests, feel free to reach out!
